from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from app.models.complaint import Complaint

def seed_database_if_empty(db: Session):
    count = db.query(Complaint).count()
    if count > 0:
        return
        
    print("[Database Seeder] Seeding database with initial complaints...")
    
    now = datetime.now()
    
    seeds = [
        Complaint(
            citizen_name="Demo Citizen",
            citizen_phone="9876543210",
            title="Water pipeline leakage",
            description="There is a massive water pipeline leakage near Shivaji Nagar bus stand. Millions of liters of clean water are being wasted. Please address this urgently.",
            latitude=18.5312,
            longitude=73.8445,
            address="Shivaji Nagar Bus Stand, Pune",
            department="Water Supply Department",
            category="Water Leakage / Deficit",
            priority="Critical",
            ai_severity="Critical",
            ai_confidence=0.95,
            ai_reason="Complaint mentions massive pipeline leakage wasting millions of liters.",
            ai_keywords="water, pipeline, leakage",
            ai_summary="Complaint mentions massive pipeline leakage wasting millions of liters.",
            priorityScore=82,
            priorityLevel="Critical",
            priorityBreakdown={
                "safetyRisk": 30,
                "publicImpact": 20,
                "essentialService": 20,
                "urgency": 10,
                "duplicates": 0,
                "location": 5,
                "timePending": 2,
                "escalationBoost": 0
            },
            status="In Progress",
            created_at=now - timedelta(days=4),
            updated_at=now - timedelta(days=3)
        ),
        Complaint(
            citizen_name="Demo Citizen",
            citizen_phone="9876543210",
            title="Street light not functioning",
            description="Three street lights are completely dark on the lane opposite to D-Mart. It is unsafe for women and children to walk at night.",
            latitude=18.5074,
            longitude=73.8077,
            address="Kothrud, Pune",
            department="Electricity Department",
            category="Power Issue",
            priority="High",
            ai_severity="Moderate",
            ai_confidence=0.88,
            ai_reason="Dark road reported causing unsafe walking conditions.",
            ai_keywords="street light, dark road",
            ai_summary="Dark road reported causing unsafe walking conditions.",
            priorityScore=55,
            priorityLevel="Medium",
            priorityBreakdown={
                "safetyRisk": 15,
                "publicImpact": 10,
                "essentialService": 20,
                "urgency": 5,
                "duplicates": 0,
                "location": 0,
                "timePending": 2,
                "escalationBoost": 0
            },
            status="Submitted",
            created_at=now - timedelta(days=2),
            updated_at=now - timedelta(days=2)
        ),
        Complaint(
            citizen_name="Aarav Sharma",
            citizen_phone="9876500000",
            title="Potholes on main road",
            description="Severe potholes on the main road causing vehicular damage and potential accidents. They have become very deep after the rain.",
            latitude=18.5679,
            longitude=73.9143,
            address="Viman Nagar, Pune",
            department="Roads and Drainage",
            category="Water Logging and Road Damage",
            priority="High",
            ai_severity="Critical",
            ai_confidence=0.92,
            ai_reason="Deep potholes causing immediate road danger and vehicle damage.",
            ai_keywords="potholes, road, vehicular damage",
            ai_summary="Deep potholes causing immediate road danger and vehicle damage.",
            priorityScore=73,
            priorityLevel="High",
            priorityBreakdown={
                "safetyRisk": 30,
                "publicImpact": 20,
                "essentialService": 0,
                "urgency": 10,
                "duplicates": 5,
                "location": 5,
                "timePending": 3,
                "escalationBoost": 0
            },
            status="Assigned",
            created_at=now - timedelta(days=1),
            updated_at=now - timedelta(hours=10)
        ),
        Complaint(
            citizen_name="Priya Patel",
            citizen_phone="9876511111",
            title="Garbage dumping on roadside",
            description="Large garbage dump has accumulated on the roadside. It emits foul smell and attracts stray dogs/insects.",
            latitude=18.5089,
            longitude=73.9258,
            address="Hadapsar, Pune",
            department="Solid Waste Management",
            category="Garbage Accumulation",
            priority="Low",
            ai_severity="Minor",
            ai_confidence=0.90,
            ai_reason="Roadside garbage accumulation attracting stray animals.",
            ai_keywords="garbage, dump, roadside",
            ai_summary="Roadside garbage accumulation attracting stray animals.",
            priorityScore=22,
            priorityLevel="Low",
            priorityBreakdown={
                "safetyRisk": 5,
                "publicImpact": 5,
                "essentialService": 0,
                "urgency": 2,
                "duplicates": 5,
                "location": 5,
                "timePending": 0,
                "escalationBoost": 0
            },
            status="Resolved",
            created_at=now - timedelta(days=6),
            updated_at=now - timedelta(days=4)
        ),
        # ── Public Health ──
        Complaint(
            citizen_name="Sneha Iyer",
            citizen_phone="9876533333",
            title="Mosquito breeding in stagnant water",
            description="Stagnant rainwater has collected in an open plot next to Sassoon Hospital and mosquitoes are breeding heavily. Several dengue cases reported in the neighbourhood. Urgent fumigation required.",
            latitude=18.5286, longitude=73.8748,
            address="Near Sassoon Hospital, Pune",
            department="Public Health", category="Mosquito Breeding / Unhygienic Site",
            priority="High", ai_severity="Critical", ai_confidence=0.91,
            ai_reason="Disease outbreak risk near a major hospital; urgent public health hazard.",
            ai_keywords="mosquito, dengue, stagnant water, hospital",
            ai_summary="Disease outbreak risk near a major hospital; urgent public health hazard.",
            priorityScore=76, priorityLevel="High",
            priorityBreakdown={"safetyRisk": 30, "publicImpact": 20, "essentialService": 20, "urgency": 10, "duplicates": 0, "location": 5, "timePending": 4, "escalationBoost": 0},
            assigned_officer="Officer Patil",
            status="Assigned",  # 5 days old High → SLA engine will auto-escalate
            created_at=now - timedelta(days=5), updated_at=now - timedelta(days=4),
        ),
        Complaint(
            citizen_name="Vikram Singh",
            citizen_phone="9876544444",
            title="Open garbage burning causing smoke",
            description="Residents are burning garbage openly every morning near the school playground. Children are inhaling toxic smoke during assembly.",
            latitude=18.4967, longitude=73.8419,
            address="Sahakar Nagar, Pune",
            department="Public Health", category="Mosquito Breeding / Unhygienic Site",
            priority="Medium", ai_severity="Moderate", ai_confidence=0.84,
            ai_reason="Health hazard from smoke inhalation near a school.",
            ai_keywords="smoke, garbage burning, school",
            ai_summary="Health hazard from smoke inhalation near a school.",
            priorityScore=48, priorityLevel="Medium",
            priorityBreakdown={"safetyRisk": 15, "publicImpact": 10, "essentialService": 0, "urgency": 5, "duplicates": 0, "location": 5, "timePending": 3, "escalationBoost": 0},
            assigned_officer="Officer Patil",
            status="Submitted",
            created_at=now - timedelta(days=3), updated_at=now - timedelta(days=3),
        ),
        # ── Traffic Police ──
        Complaint(
            citizen_name="Rohan Verma",
            citizen_phone="9876522222",
            title="Broken traffic signal causing daily jams",
            description="The traffic signal at Swargate junction has been blinking amber for a week. Massive jams every rush hour and two minor accidents already.",
            latitude=18.5018, longitude=73.8636,
            address="Swargate Junction, Pune",
            department="Traffic Police", category="Traffic Congestion",
            priority="Medium", ai_severity="Moderate", ai_confidence=0.87,
            ai_reason="Faulty signal causing congestion and accident risk at a major junction.",
            ai_keywords="traffic signal, jam, junction",
            ai_summary="Faulty signal causing congestion and accident risk at a major junction.",
            priorityScore=52, priorityLevel="Medium",
            priorityBreakdown={"safetyRisk": 15, "publicImpact": 20, "essentialService": 0, "urgency": 5, "duplicates": 0, "location": 5, "timePending": 3, "escalationBoost": 0},
            assigned_officer="Officer Deshpande",
            status="In Progress",
            created_at=now - timedelta(days=3), updated_at=now - timedelta(days=1),
        ),
        Complaint(
            citizen_name="Demo Citizen",
            citizen_phone="9876543210",
            title="Illegal parking blocking ambulance route",
            description="Cars are parked illegally on both sides of the lane behind Ruby Hall Clinic, blocking the ambulance route. This is life-threatening during emergencies.",
            latitude=18.5308, longitude=73.8770,
            address="Behind Ruby Hall Clinic, Pune",
            department="Traffic Police", category="Traffic Congestion",
            priority="High", ai_severity="Critical", ai_confidence=0.93,
            ai_reason="Emergency access route blocked near a hospital.",
            ai_keywords="illegal parking, ambulance, hospital",
            ai_summary="Emergency access route blocked near a hospital.",
            priorityScore=71, priorityLevel="High",
            priorityBreakdown={"safetyRisk": 30, "publicImpact": 10, "essentialService": 0, "urgency": 10, "duplicates": 0, "location": 5, "timePending": 4, "escalationBoost": 0},
            assigned_officer="Officer Deshpande",
            status="Resolved",  # demo citizen can confirm & rate this live in the demo
            created_at=now - timedelta(days=9), updated_at=now - timedelta(days=1),
        ),
        # ── Electricity ──
        Complaint(
            citizen_name="Anita Kulkarni",
            citizen_phone="9876555555",
            title="Transformer sparking near school gate",
            description="The distribution transformer outside the municipal school gate is sparking loudly and smoking. Children pass within a few feet of it every day. Extremely dangerous.",
            latitude=18.5523, longitude=73.8912,
            address="Municipal School, Yerawada, Pune",
            department="Electricity Department", category="Power Issue",
            priority="Critical", ai_severity="Critical", ai_confidence=0.96,
            ai_reason="Live electrical hazard beside a school; risk of electrocution and fire.",
            ai_keywords="transformer, sparking, school, electrocution",
            ai_summary="Live electrical hazard beside a school; risk of electrocution and fire.",
            priorityScore=88, priorityLevel="Critical",
            priorityBreakdown={"safetyRisk": 30, "publicImpact": 20, "essentialService": 20, "urgency": 10, "duplicates": 0, "location": 5, "timePending": 2, "escalationBoost": 0},
            assigned_officer="Officer Sharma",
            status="Assigned",  # 2 days old Critical (24h SLA) → auto-escalates
            created_at=now - timedelta(days=2), updated_at=now - timedelta(days=2),
        ),
        Complaint(
            citizen_name="Demo Citizen",
            citizen_phone="9876543210",
            title="Frequent power cuts every evening",
            description="Our lane has been facing 2-3 hour power cuts every evening for the past two weeks. Students cannot study and inverters have stopped coping.",
            latitude=18.5121, longitude=73.8232,
            address="Karve Nagar, Pune",
            department="Electricity Department", category="Power Issue",
            priority="Medium", ai_severity="Moderate", ai_confidence=0.85,
            ai_reason="Recurring outages disrupting an essential service for a residential area.",
            ai_keywords="power cut, outage, evening",
            ai_summary="Recurring outages disrupting an essential service for a residential area.",
            priorityScore=58, priorityLevel="Medium",
            priorityBreakdown={"safetyRisk": 15, "publicImpact": 10, "essentialService": 20, "urgency": 5, "duplicates": 0, "location": 0, "timePending": 5, "escalationBoost": 0},
            assigned_officer="Officer Sharma",
            status="Closed", rating=4, feedback="Supply restored and stable for three days now. Thanks for the quick escalation.",
            created_at=now - timedelta(days=12), updated_at=now - timedelta(days=2),
        ),
        # ── Water Supply ──
        Complaint(
            citizen_name="Rohan Verma",
            citizen_phone="9876522222",
            title="No water supply for three days",
            description="Our entire housing society has had no municipal water supply for three days. Tankers are charging exorbitant rates. Over 80 families affected.",
            latitude=18.5605, longitude=73.7769,
            address="Baner, Pune",
            department="Water Supply Department", category="Water Leakage / Deficit",
            priority="High", ai_severity="Major", ai_confidence=0.9,
            ai_reason="Essential water service outage affecting a large residential community.",
            ai_keywords="no water, supply, society",
            ai_summary="Essential water service outage affecting a large residential community.",
            priorityScore=68, priorityLevel="High",
            priorityBreakdown={"safetyRisk": 15, "publicImpact": 20, "essentialService": 20, "urgency": 10, "duplicates": 0, "location": 0, "timePending": 1, "escalationBoost": 0},
            assigned_officer="Officer Patil",
            status="Submitted",
            created_at=now - timedelta(days=1), updated_at=now - timedelta(days=1),
        ),
        Complaint(
            citizen_name="Sneha Iyer",
            citizen_phone="9876533333",
            title="Contaminated drinking water",
            description="Tap water in our area has been muddy and foul-smelling for a week. Several residents reported stomach infections. Water testing urgently needed.",
            latitude=18.4899, longitude=73.8567,
            address="Bibwewadi, Pune",
            department="Water Supply Department", category="Water Leakage / Deficit",
            priority="Critical", ai_severity="Critical", ai_confidence=0.94,
            ai_reason="Contaminated drinking water causing illness — severe public health risk.",
            ai_keywords="contaminated, water, infection",
            ai_summary="Contaminated drinking water causing illness — severe public health risk.",
            priorityScore=85, priorityLevel="Critical",
            priorityBreakdown={"safetyRisk": 30, "publicImpact": 20, "essentialService": 20, "urgency": 10, "duplicates": 0, "location": 0, "timePending": 5, "escalationBoost": 0},
            assigned_officer="Officer Patil",
            status="Closed", rating=5, feedback="Pipeline flushed and clean water restored. Excellent response after escalation.",
            created_at=now - timedelta(days=13), updated_at=now - timedelta(days=6),
        ),
        # ── Roads and Drainage ──
        Complaint(
            citizen_name="Vikram Singh",
            citizen_phone="9876544444",
            title="Blocked drain overflowing sewage onto street",
            description="The main storm drain on Laxmi Road is completely blocked and raw sewage is overflowing onto the shopping street. Foot traffic is wading through sewage.",
            latitude=18.5158, longitude=73.8535,
            address="Laxmi Road, Pune",
            department="Roads and Drainage", category="Water Logging and Road Damage",
            priority="High", ai_severity="Major", ai_confidence=0.89,
            ai_reason="Sewage overflow in a dense market street; sanitation and mobility hazard.",
            ai_keywords="drain, sewage, overflow, market",
            ai_summary="Sewage overflow in a dense market street; sanitation and mobility hazard.",
            priorityScore=70, priorityLevel="High",
            priorityBreakdown={"safetyRisk": 15, "publicImpact": 20, "essentialService": 0, "urgency": 10, "duplicates": 5, "location": 5, "timePending": 5, "escalationBoost": 0},
            assigned_officer="Officer Deshpande",
            status="In Progress",  # 8 days old High (72h SLA) → auto-escalates
            created_at=now - timedelta(days=8), updated_at=now - timedelta(days=5),
        ),
        # ── Solid Waste Management ──
        Complaint(
            citizen_name="Anita Kulkarni",
            citizen_phone="9876555555",
            title="Community dustbins overflowing for a week",
            description="All four community dustbins in our lane have been overflowing for a week. Collection truck has not come. Stray cattle are scattering the waste everywhere.",
            latitude=18.5433, longitude=73.8302,
            address="Aundh, Pune",
            department="Solid Waste Management", category="Garbage Accumulation",
            priority="Medium", ai_severity="Moderate", ai_confidence=0.86,
            ai_reason="Missed collections causing accumulating waste and hygiene issues.",
            ai_keywords="dustbin, overflowing, collection",
            ai_summary="Missed collections causing accumulating waste and hygiene issues.",
            priorityScore=42, priorityLevel="Medium",
            priorityBreakdown={"safetyRisk": 5, "publicImpact": 10, "essentialService": 0, "urgency": 5, "duplicates": 5, "location": 0, "timePending": 5, "escalationBoost": 0},
            assigned_officer="Officer Sharma",
            status="Submitted",
            created_at=now - timedelta(hours=8), updated_at=now - timedelta(hours=8),
        ),
    ]

    db.add_all(seeds)
    db.commit()
    print(f"[Database Seeder] Seeding finished successfully. Inserted {len(seeds)} complaints.")
